const riskMatrix = [
  {
    id: 1,
    title: 'Risk 1',
    requirement: ' Requirement Description for Risk 1',
    technology: ['sql', 'aws'],
    associatedRisk: [],
    impact: 'low',
    probability: 'low',
    measures: ['measure risk with technique 1 bi-weekly'],
    mitigation: ['This is the plan to try to avoid the risks, some details here'],
    exposure: 50,
  },
  {
    id: 2,
    title: 'Risk 2',
    requirement: ' Requirement Description for Risk 2',
    technology: ['java', 'sql', 'aws'],
    associatedRisk: [],
    impact: 'low',
    probability: 'moderate',
    measures: ['measure risk with technique 2 weekly'],
    mitigation: ['This is the plan to try to avoid the risks, some details here'],
    exposure: 80,
  },
  {
    id: 3,
    title: 'Risk 3',
    requirement: ' Requirement Description for Risk 3, but it is linked with Risk 1',
    technology: ['sql', 'react', 'aws'],
    associatedRisk: [1],
    impact: 'medium',
    probability: 'moderate',
    measures: ['measure risk with technique 1 and 2 weekly'],
    mitigation: ['This is the plan to try to avoid the risks, some details here'],
    exposure: 100,
  },
  {
    id: 4,
    title: 'Risk 4',
    requirement: ' Requirement Description for Risk 3, but it is linked with Risk 2 and 1',
    technology: ['java', 'sql', 'react', 'aws'],
    associatedRisk: [2, 1],
    impact: 'high',
    probability: 'very low',
    measures: ['measure risk with technique 1'],
    mitigation: ['This is the plan to try to avoid the risks, some details here'],
    exposure: 180,
  },
  {
    id: 5,
    title: 'Risk 5',
    requirement: 'This risks is not clear and there is no data for requirement',
    technology: ['java', 'sql', 'react', 'aws', 'azure', 'html'],
    associatedRisk: [],
    impact: 'high',
    probability: 'very high',
    measures: ['measure risk with technique 1', 'monitor aws dashboard'],
    mitigation: ['This is the plan to try to avoid the risks, some details here'],
    exposure: 300,
  },
];

module.exports = riskMatrix;
