const riskMatrix = [
  {
    id: 1,
    title: 'Risk 1',
    type: 'treat',
    requirement: ' Requirement Description for Risk 1',
    technology: ['sql', 'aws'],
    associatedRisk: [],
    impact: 'low',
    probability: 'low',
    measures: ['measure risk with technique 1 bi-weekly'],
    mitigation: ['This is the plan to try to avoid the risks, some details here'],
    projects: [
      { id: 1, exposure: 50 },
      { id: 2, exposure: 80 },
      { id: 3, exposure: 10 },
    ],
  },
  {
    id: 2,
    title: 'Risk 2',
    type: 'treat',
    requirement: ' Requirement Description for Risk 2',
    technology: ['java', 'sql', 'aws'],
    associatedRisk: [],
    impact: 'low',
    probability: 'moderate',
    measures: ['measure risk with technique 2 weekly'],
    mitigation: ['This is the plan to try to avoid the risks, some details here'],
    projects: [
      { id: 1, exposure: 80 },
      { id: 2, exposure: 80 },
      { id: 3, exposure: 50 },
    ],
  },
  {
    id: 3,
    title: 'Risk 3',
    type: 'opportunity',
    requirement: ' Requirement Description for Risk 3, but it is linked with Risk 1',
    technology: ['sql', 'react', 'aws'],
    associatedRisk: [1],
    impact: 'medium',
    probability: 'moderate',
    measures: ['measure risk with technique 1 and 2 weekly'],
    mitigation: ['This is the plan to try to avoid the risks, some details here'],
    projects: [{ id: 1, exposure: 100 }],
  },
  {
    id: 4,
    title: 'Risk 4',
    type: 'opportunity',
    requirement: ' Requirement Description for Risk 3, but it is linked with Risk 2 and 1',
    technology: ['java', 'sql', 'react', 'aws'],
    associatedRisk: [2, 1],
    impact: 'high',
    probability: 'very low',
    measures: ['measure risk with technique 1'],
    mitigation: ['This is the plan to try to avoid the risks, some details here'],
    projects: [
      { id: 2, exposure: 150 },
      { id: 4, exposure: 180 },
      { id: 5, exposure: 110 },
    ],
  },
  {
    id: 5,
    title: 'Risk 5',
    type: 'opportunity',
    requirement: 'This risks is not clear and there is no data for requirement',
    technology: ['java', 'sql', 'react', 'aws', 'azure', 'html'],
    associatedRisk: [],
    impact: 'high',
    probability: 'very high',
    measures: ['measure risk with technique 1', 'monitor aws dashboard'],
    mitigation: ['This is the plan to try to avoid the risks, some details here'],
    projects: [
      { id: 1, exposure: 300 },
      { id: 6, exposure: 280 },
    ],
  },
  {
    id: 6,
    title: 'Risk 6',
    type: 'treat',
    requirement: ' Requirement Description for Risk 3, but it is linked with Risk 2 and 1',
    technology: ['Lorem', 'Ipsum', 'react'],
    associatedRisk: [1, 3, 5],
    impact: 'high',
    probability: 'high',
    measures: ['Nullam et pretium eros, a ornare eros.'],
    mitigation: ['n/a'],
    projects: [
      { id: 4, exposure: 280 },
      { id: 3, exposure: 210 },
    ],
  },
  {
    id: 7,
    title: 'Risk 7',
    type: 'treat',
    requirement: 'This risks is not clear and there is no data for requirement',
    technology: ['Lorem', 'Ipsum', 'react'],
    associatedRisk: [6],
    impact: 'high',
    probability: 'very low',
    measures: [
      'n pellentesque nisi eget orci venenatis',
      'efficitur lobortis nunc volutpat.',
      'Sed at consectetur erat.',
    ],
    mitigation: [
      'In non feugiat magna, a lacinia est. Morbi vitae augue ornare tortor convallis consectetur id ac orci. Sed velit sem, lobortis sit amet imperdiet quis, porttitor quis nulla. Praesent ornare cursus fringilla. Sed ac augue ut augue dictum condimentum ut eget eros. Fusce gravida dignissim augue in malesuada. Fusce at lobortis leo.',
    ],
    projects: [
      { id: 1, exposure: 150 },
      { id: 2, exposure: 180 },
      { id: 3, exposure: 110 },
      { id: 4, exposure: 110 },
      { id: 5, exposure: 90 },
    ],
  },
];

module.exports = riskMatrix;
